import * as path from "node:path";
import * as vscode from "vscode";

const CHECK_BYTE_COUNT = 1024;
const HEADER_LINE_LIMIT = 40;
const KNOWN_GENERATOR_PATTERN =
  "(?:protoc(?:-gen-[\\w-]+)?|sqlc|buf|swagger(?:-codegen)?|openapi(?:-generator)?|grpc-gateway|mockery|stringer|easyjson|deepcopy-gen|defaulter-gen|conversion-gen|client-gen|lister-gen|informer-gen|kysely-codegen|napi-rs)";

const AUTO_GENERATED_HEADER_MARKERS: readonly RegExp[] = [
  /@generated\b/i,
  /\bcode\s+generated\s+by\s+[a-z0-9_.-]+/i,
  /\bthis\s+file\s+was\s+automatically\s+generated\b/i,
  new RegExp(`\\bgenerated\\s+by\\s+${KNOWN_GENERATOR_PATTERN}\\b`, "i"),
];

const AUTO_GENERATED_FILENAME_PATTERNS: readonly RegExp[] = [
  /^zz_generated\./,
  /\.pb\.(go|cc|h|c|js|ts)$/,
  /_pb2\.py$/,
  /_pb2_grpc\.py$/,
  /\.gen\.(go|ts|js|py)$/,
  /^generated\.(go|ts|js|py)$/,
  /\.swagger\.json$/,
  /\.openapi\.json$/,
  /\.mock\.(go|ts)$/,
  /\.mocks?\.(go|ts|js)$/,
];

type CommentStyle = "slash" | "hash" | "sql" | "html";

const COMMENT_STYLES_BY_EXTENSION = new Map<string, readonly CommentStyle[]>([
  [".c", ["slash"]],
  [".cc", ["slash"]],
  [".cpp", ["slash"]],
  [".cs", ["slash"]],
  [".dart", ["slash"]],
  [".go", ["slash"]],
  [".h", ["slash"]],
  [".hpp", ["slash"]],
  [".java", ["slash"]],
  [".js", ["slash"]],
  [".jsx", ["slash"]],
  [".kt", ["slash"]],
  [".kts", ["slash"]],
  [".mjs", ["slash"]],
  [".cjs", ["slash"]],
  [".php", ["slash"]],
  [".rs", ["slash"]],
  [".scala", ["slash"]],
  [".swift", ["slash"]],
  [".ts", ["slash"]],
  [".tsx", ["slash"]],
  [".py", ["hash"]],
  [".rb", ["hash"]],
  [".sh", ["hash"]],
  [".bash", ["hash"]],
  [".zsh", ["hash"]],
  [".yml", ["hash"]],
  [".yaml", ["hash"]],
  [".toml", ["hash"]],
  [".ini", ["hash"]],
  [".cfg", ["hash"]],
  [".conf", ["hash"]],
  [".env", ["hash"]],
  [".pl", ["hash"]],
  [".r", ["hash"]],
  [".sql", ["sql"]],
  [".html", ["html"]],
  [".htm", ["html"]],
  [".xml", ["html"]],
  [".svg", ["html"]],
  [".xhtml", ["html"]],
]);

const COMMENT_STYLES_BY_BASENAME = new Map<string, readonly CommentStyle[]>([
  ["dockerfile", ["hash"]],
  ["makefile", ["hash"]],
  ["justfile", ["hash"]],
]);

export async function assertWritableGeneratedFile(uri: vscode.Uri, displayPath: string, overwriteGenerated?: boolean): Promise<void> {
  if (overwriteGenerated === true) return;

  const fileNameMarker = detectAutoGeneratedFilename(displayPath);
  if (fileNameMarker) throw generatedFileError(displayPath, fileNameMarker);

  let bytes: Uint8Array;
  try {
    bytes = await vscode.workspace.fs.readFile(uri);
  } catch {
    return;
  }

  const prefix = Buffer.from(bytes.subarray(0, CHECK_BYTE_COUNT)).toString("utf8");
  const marker = detectAutoGeneratedMarker(prefix, displayPath);
  if (marker) throw generatedFileError(displayPath, marker);
}

export function assertWritableGeneratedContent(content: string, displayPath: string, overwriteGenerated?: boolean): void {
  if (overwriteGenerated === true) return;
  const marker = detectAutoGeneratedMarker(content.slice(0, CHECK_BYTE_COUNT), displayPath);
  if (marker) throw generatedFileError(displayPath, marker);
}

function detectAutoGeneratedFilename(filePath: string): string | undefined {
  const fileName = filePath.replace(/\\/g, "/").split("/").pop()?.toLowerCase() ?? "";
  return AUTO_GENERATED_FILENAME_PATTERNS.some((pattern) => pattern.test(fileName)) ? fileName : undefined;
}

function detectAutoGeneratedMarker(content: string, filePath: string): string | undefined {
  const commentStyles = getCommentStylesForPath(filePath);
  const headerCommentText = extractLeadingHeaderCommentText(content, commentStyles);
  if (!headerCommentText) return undefined;

  for (const markerPattern of AUTO_GENERATED_HEADER_MARKERS) {
    const match = markerPattern.exec(headerCommentText);
    if (match?.[0]) return match[0];
  }

  return undefined;
}

function getCommentStylesForPath(filePath: string): readonly CommentStyle[] {
  const normalizedPath = filePath.toLowerCase();
  const fileName = path.basename(normalizedPath);
  const stylesByName = COMMENT_STYLES_BY_BASENAME.get(fileName);
  if (stylesByName) return stylesByName;

  const ext = path.extname(fileName);
  return COMMENT_STYLES_BY_EXTENSION.get(ext) ?? [];
}

function extractLeadingHeaderCommentText(content: string, commentStyles: readonly CommentStyle[]): string {
  if (commentStyles.length === 0) return "";

  const includeSlash = commentStyles.includes("slash");
  const includeHash = commentStyles.includes("hash");
  const includeSql = commentStyles.includes("sql");
  const includeHtml = commentStyles.includes("html");
  const lines = stripBom(content).split(/\r?\n/);
  const headerLines: string[] = [];
  let started = false;
  let inSlashBlock = false;
  let inHtmlBlock = false;

  for (let lineIndex = 0; lineIndex < lines.length && lineIndex < HEADER_LINE_LIMIT; lineIndex++) {
    const trimmed = lines[lineIndex]?.trim() ?? "";
    if (lineIndex === 0 && trimmed.startsWith("#!")) continue;

    if (inSlashBlock) {
      headerLines.push(trimmed);
      if (trimmed.includes("*/")) inSlashBlock = false;
      continue;
    }

    if (inHtmlBlock) {
      headerLines.push(trimmed);
      if (trimmed.includes("-->")) inHtmlBlock = false;
      continue;
    }

    if (trimmed.length === 0) {
      if (started) headerLines.push("");
      continue;
    }

    if (includeSlash && trimmed.startsWith("//")) {
      started = true;
      headerLines.push(trimmed);
      continue;
    }

    if (includeSlash && trimmed.startsWith("/*")) {
      started = true;
      headerLines.push(trimmed);
      if (!trimmed.includes("*/")) inSlashBlock = true;
      continue;
    }

    if (includeHash && trimmed.startsWith("#")) {
      started = true;
      headerLines.push(trimmed);
      continue;
    }

    if (includeSql && trimmed.startsWith("--")) {
      started = true;
      headerLines.push(trimmed);
      continue;
    }

    if (includeHtml && trimmed.startsWith("<!--")) {
      started = true;
      headerLines.push(trimmed);
      if (!trimmed.includes("-->")) inHtmlBlock = true;
      continue;
    }

    break;
  }

  return headerLines.join("\n");
}

function stripBom(content: string): string {
  return content.charCodeAt(0) === 0xfeff ? content.slice(1) : content;
}

function generatedFileError(displayPath: string, detected: string): Error {
  return new Error(
    [
      `Cannot modify auto-generated file: ${displayPath}`,
      "",
      `This file appears to be automatically generated (detected marker: "${detected}").`,
      "Change the source or generator configuration and regenerate the file, or pass overwriteGenerated=true when this overwrite is intentional.",
    ].join("\n"),
  );
}
