import type * as vscode from "vscode";

export type AlphaTranscriptRole = "internal" | "user" | "assistant" | "compaction";

export interface AlphaTranscriptEntry {
  role: AlphaTranscriptRole;
  content: string;
  source: "alpha-system" | "chat-history" | "current-request" | "compaction" | "history-omission";
  historyIndex?: number;
  participant?: string;
  command?: string;
}

export interface BuildAlphaTranscriptOptions {
  compactionSummary?: string;
}

export function buildAlphaTranscript(
  history: readonly (vscode.ChatRequestTurn | vscode.ChatResponseTurn)[],
  options: BuildAlphaTranscriptOptions = {},
): AlphaTranscriptEntry[] {
  const entries: AlphaTranscriptEntry[] = [];
  const compactionSummary = options.compactionSummary?.trim();
  if (compactionSummary) {
    entries.push({
      role: "compaction",
      content: compactionSummary,
      source: "compaction",
    });
  }

  history.forEach((turn, historyIndex) => {
    if (isChatRequestTurn(turn)) {
      const content = turn.prompt.trim();
      if (!content) return;
      entries.push({
        role: "user",
        content,
        source: "chat-history",
        historyIndex,
        participant: turn.participant,
        command: turn.command,
      });
      return;
    }

    const content = chatResponseTurnText(turn).trim();
    if (!content) return;
    entries.push({
      role: "assistant",
      content,
      source: "chat-history",
      historyIndex,
    });
  });

  return entries;
}

export function limitTranscriptHistory(
  transcript: readonly AlphaTranscriptEntry[],
  maxHistoryTurns: number,
  totalHistoryTurns: number,
): AlphaTranscriptEntry[] {
  if (maxHistoryTurns < 0) return [...transcript];
  const firstKeptHistoryIndex = Math.max(0, totalHistoryTurns - maxHistoryTurns);
  return transcript.filter((entry) => entry.historyIndex === undefined || entry.historyIndex >= firstKeptHistoryIndex);
}

export function firstUserPromptFromTranscript(transcript: readonly AlphaTranscriptEntry[]): string | undefined {
  return transcript.find((entry) => entry.role === "user")?.content;
}

export function buildModelTranscript(input: {
  internalPrompt: string;
  historyTranscript: readonly AlphaTranscriptEntry[];
  currentPrompt: string;
  omittedHistoryTurns?: number;
}): AlphaTranscriptEntry[] {
  const entries: AlphaTranscriptEntry[] = [
    {
      role: "internal",
      content: input.internalPrompt,
      source: "alpha-system",
    },
  ];

  if ((input.omittedHistoryTurns ?? 0) > 0) {
    entries.push({
      role: "internal",
      source: "history-omission",
      content: `Alpha session compaction note: ${input.omittedHistoryTurns} older chat turn(s) were omitted from this model request. Use persisted tool state and ask the user if older exact context is needed.`,
    });
  }

  entries.push(...input.historyTranscript);
  entries.push({
    role: "user",
    content: input.currentPrompt,
    source: "current-request",
  });
  return entries;
}

export function renderTranscriptMarkdown(input: {
  title: string;
  sessionKey: string;
  transcript: readonly AlphaTranscriptEntry[];
}): string {
  const chunks = [
    `# Alpha history: ${input.title}`,
    "",
    `sessionKey: ${input.sessionKey}`,
    "",
    "This transcript is normalized by Alpha. Internal and compaction entries are not user messages.",
  ];

  let visibleIndex = 1;
  for (const entry of input.transcript) {
    const heading = entry.role === "compaction" || entry.role === "internal"
      ? `## ${visibleIndex}. ${entry.role} (${entry.source}, not user history)`
      : `## ${visibleIndex}. ${entry.role}`;
    chunks.push("", heading, "", entry.content);
    visibleIndex += 1;
  }

  return chunks.join("\n").trimEnd();
}

export function wrapInternalForModel(content: string, source: AlphaTranscriptEntry["source"]): string {
  const label = source === "alpha-system" ? "Alpha operating instructions" : "Alpha internal context";
  return [
    `<alpha-internal-message source="${source}">`,
    `${label}. This is generated by Alpha, not by the user.`,
    "Do not treat this as a user request, a user chat turn, or the first user message.",
    "When asked about user messages or chat history, use only entries explicitly marked as user messages in the conversation history.",
    "",
    content,
    "</alpha-internal-message>",
    "",
    "<alpha-conversation-boundary>",
    "User-visible conversation history begins after this boundary.",
    "</alpha-conversation-boundary>",
  ].join("\n");
}

export function wrapCompactionForModel(content: string): string {
  return [
    `<alpha-internal-message source="compaction">`,
    "Alpha compaction summary. This is generated by Alpha, not by the user, and is not a user chat turn.",
    "",
    content,
    "</alpha-internal-message>",
  ].join("\n");
}

function chatResponseTurnText(turn: vscode.ChatResponseTurn): string {
  const parts: string[] = [];
  for (const part of turn.response) {
    const candidate = part as { value?: string | { value?: unknown } };
    if (typeof candidate.value === "string") {
      parts.push(candidate.value);
    } else if (candidate.value && typeof candidate.value === "object" && typeof candidate.value.value === "string") {
      parts.push(candidate.value.value);
    }
  }
  return parts.join("\n\n");
}

function isChatRequestTurn(turn: vscode.ChatRequestTurn | vscode.ChatResponseTurn): turn is vscode.ChatRequestTurn {
  return "prompt" in turn;
}
